{
  "type": "record",
  "name": "BiciDevuelta",
  "namespace": "com.citypass.movilidad.events",
  "doc": "Evento emitido cuando una bicicleta publica es devuelta en una estacion",
  "fields": [
    {"name": "eventId", "type": "string"},
    {"name": "eventType", "type": "string"},
    {"name": "timestamp", "type": "string"},
    {"name": "source", "type": "string"},
    {"name": "userId", "type": "string"},
    {"name": "biciId", "type": "string"},
    {"name": "estacionDevolucionId", "type": "string"},
    {"name": "estacionDevolucionNombre", "type": "string"},
    {"name": "duracionMinutos", "type": "int"},
    {"name": "distanciaKm", "type": "double"}
  ]
}
